### ISSUE TITLE
Tdex-daemon unexpected crash after calling sell grpc function

### ISSUE THREAD

**Issue by IlSassone** [tdex-network/tdex-daemon#541]
With this request payload of `trade.sell` method of the TypeScript `tdex-sdk` module :
```
{
  "market": {
    "quoteAsset": "30973a9164ea895605161bb9f81c87938984620e102fa95f2564bd5ddf4ca5e1",
    "provider": "Tdex test",
    "feeBasisPoint": 25,
    "baseAsset": "5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225"
  },
  "amount": 50000000,
  "asset": "5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225",
  "identity": {
    "type": 4,
    "restorer": {
      "esploraEndpoint": "http://localhost:5001"
    },
    "network": {
      "messagePrefix": "\u0018Liquid Signed Message:\n",
      "bech32": "ert",
      "blech32": "el",
      "bip32": {
        "public": 70617039,
        "private": 70615956
      },
      "pubKeyHash": 235,
      "scriptHash": 75,
      "wif": 239,
      "confidentialPrefix": 4,
      "assetHash": "5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225"
    },
    "isRestored": {
      "_h": 0,
      "_i": 1,
      "_j": true,
      "_k": null
    }
  }
}
```
The daemon crashes and after restarting it is still broken and I've had to delete and create the container again.
The version that I'm using is 0.8.1
These are the logs that i can see:
```
panic: runtime error: index out of range [0] with length 0

goroutine 4603 [running]:

github.com/tdex-network/tdex-daemon/pkg/wallet.extractScriptTypesFromPset(0x400043da40, 0x459d50, 0x40101f7f00, 0x10, 0x10, 0xcce920, 0xcce920, 0x14d6060, 0x0, 0x0, ...)

/tdex-daemon/pkg/wallet/util.go:192 +0xc14

github.com/tdex-network/tdex-daemon/pkg/wallet.calcFeeAmount(0x400043da40, 0x1, 0x1, 0x64, 0x1)

/tdex-daemon/pkg/wallet/util.go:252 +0x30

github.com/tdex-network/tdex-daemon/pkg/wallet.(*Wallet).UpdateTx(0x40000af560, 0x4010397a80, 0x198c, 0x4010287680, 0x3, 0x3, 0x0, 0x0, 0x0, 0x4010287bf0, ...)

/tdex-daemon/pkg/wallet/transaction.go:429 +0x8d4

github.com/tdex-network/tdex-daemon/internal/core/application.fillProposal(0x40006d4900, 0x18, 0x18, 0xfa8068, 0x400067d0e0, 0x4010320800, 0x4, 0x4, 0x4010287680, 0x3, ...)

/tdex-daemon/internal/core/application/trade_service.go:675 +0x3b8

github.com/tdex-network/tdex-daemon/internal/core/application.tradeManager.FillProposal(...)

/tdex-daemon/internal/core/application/types.go:377

github.com/tdex-network/tdex-daemon/internal/core/application.(*tradeService).TradePropose(0x4000090880, 0xfa0f20, 0x4010237d10, 0x4000686c40, 0x40, 0x4000686c80, 0x40, 0x1, 0xfa8068, 0x400067d0e0, ...)

/tdex-daemon/internal/core/application/trade_service.go:342 +0x8cc

github.com/tdex-network/tdex-daemon/internal/interfaces/grpc/handler.traderHandler.proposeTrade(0xfa3078, 0x4000090880, 0xfa0f20, 0x4010237d10, 0x401021f948, 0x419328, 0x400011f490, 0x10)

/tdex-daemon/internal/interfaces/grpc/handler/trade.go:221 +0x228

github.com/tdex-network/tdex-daemon/internal/interfaces/grpc/handler.traderHandler.tradePropose(0xfa3078, 0x4000090880, 0xfa70c8, 0x400011f490, 0x4000569400, 0xcc7920, 0xcba901)

/tdex-daemon/internal/interfaces/grpc/handler/trade.go:298 +0x94

github.com/tdex-network/tdex-daemon/internal/interfaces/grpc/handler.traderHandler.TradePropose(...)

/tdex-daemon/internal/interfaces/grpc/handler/trade.go:64

github.com/tdex-network/tdex-protobuf/generated/go/trade._Trade_TradePropose_Handler(0xcf73a0, 0x400038ae10, 0xfa4a50, 0x40006a60c0, 0x40001f2040, 0xd2f540)

/go/pkg/mod/github.com/tdex-network/tdex-protobuf@v0.0.0-20211025103804-7ead2ca5a7b3/generated/go/trade/trade_grpc.pb.go:314 +0xf8

github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1(0xcf73a0, 0x400038ae10, 0xfa4a50, 0x40006a60c0, 0x1, 0x50)

/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:71 +0xe8

github.com/tdex-network/tdex-daemon/internal/interfaces/grpc/interceptor.streamLogger(0xcf73a0, 0x400038ae10, 0xfa4a50, 0x40006a60c0, 0x40006530e0, 0x4000116b90, 0x48, 0xffff98623f18)

/tdex-daemon/internal/interfaces/grpc/interceptor/logger.go:27 +0xa8

github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1(0xcf73a0, 0x400038ae10, 0xfa4a50, 0x40006a60c0, 0x0, 0x0)

/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:74 +0x90

github.com/tdex-network/tdex-daemon/internal/interfaces/grpc/interceptor.streamMacaroonAuthHandler.func1(0xcf73a0, 0x400038ae10, 0xfa4a50, 0x40006a60c0, 0x40006530e0, 0x4000116b90, 0x40106bb408, 0x9002bc)

/tdex-daemon/internal/interfaces/grpc/interceptor/auth.go:42 +0xb8

github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1(0xcf73a0, 0x400038ae10, 0xfa4a50, 0x40006a60c0, 0x40006530e0, 0xec5f58, 0xfa0f20, 0x4010237d10)

/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:79 +0x138

google.golang.org/grpc.(*Server).processStreamingRPC(0x40003c6c40, 0xfa8a38, 0x401133e780, 0x40006547e0, 0x4000126b40, 0x143e2a0, 0x0, 0x0, 0x0)

/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1557 +0x574

google.golang.org/grpc.(*Server).handleStream(0x40003c6c40, 0xfa8a38, 0x401133e780, 0x40006547e0, 0x0)

/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1630 +0xa28

google.golang.org/grpc.(*Server).serveStreams.func1.2(0x400043b280, 0x40003c6c40, 0xfa8a38, 0x401133e780, 0x40006547e0)

/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:941 +0x94

created by google.golang.org/grpc.(*Server).serveStreams.func1

/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:939 +0x1f8
```

**Comment by tiero** [comment]
Can you share also:

- how you running the container? ie. the ENV VAR you passing to `tdexd`
- which version of the `tdex-sdk` npm module you using?

**Comment by tiero** [comment]
assiging to @altafan from @sekulicd

**Comment by altafan** [comment]
`identity.restorer.esploraEndpoint` doesn't seem correct, it should be `http://localhost:3001`.

Can you share also the partial transaction of the request?

**Comment by IlSassone** [comment]
Ok this is the transaction that we are sending via grpc:
```
cHNldP8BALoCAAAAAAFQo5WlWQER2Ym3ghda4ozhc1XwhU9hhA0dahfI5lZU4AAAAAAA/////wIBu2f0+zST5n4KaMKLjW63rHHOw2SbI8wZykyFGweqQ1UBAAAAqfLFdaAAF6kUZijGKT18vjv0+n66iQQ8MT3JdwiHASWyUQcOKcoZBDzzPM1zJOLdqwPsxK4LXnfE/A5c9slaAQAAAAAEeGjAABepFB8lUfufBxlMLlwuV3W7grw+lDrdhwAAAAAAAQH9EBELXsA0oxNYpKgfBhvBBc0yCjBt4raPR1fciuB2Ifiln3EJF4muqWg6xDJAFJYlHB71b1I+GMAlIS5yVULrJkAOK0MCDE6SE/FLzZMFg81Tipy59qlnoDDbuyMx5ADzb6Fsd0kXqRRK/hXVSjm4FyrOGUQPojRqGwGYmIdDAQABgVAL4x4wk7NP2DQIEQc5KQ3tP5Rxr0VNKTh9RbUrzsF1NwH5LO67PN1cC2lQNJb7Y6fKITs8otGK8g3ais0ggP1OEGAzAAAAAAAAAAHWbiMBCvyYguG2a7tvr5ZpPXJIy1F1Dz45zX+kRFXrxtdp85WNcXKgwYtKZOkyuBYQepA3TDsuc3qlvthfYdlkdBH4ZUEQndAE3RJbhqF1wMlXzrAlVxGqDWDh1mLAXKjo7nMaLhU8ZmFBCXl8qIa0NIsiIhCgRQAF8GxT6PvooGxURMhUQINIyVnuoZP55hd1JS1M3F/9QBZGK3E2e9Qwgf267w8LalmdT+qxbzeWdK12Rg0w6lv174QogTqgzgF74CKg7UdQpAhPW70RN3esUGmfwn7klxb+sd7t/jNQ0/WZ9kP9437RV8PpP5/OpfGYvcJar9ZyGa1jTtsUazUMsuk54B0dp7wvnDXEbwCG6hvHWmQcF93vrnkrpbL8B2zzWZxdrTOdW4U6Yj+khTIFyUWjtOp5DhEKUHUBhMtzuQMQvGY4dEkwuKz0p77OpVJ+nLAJsmP5BjQSgxZ3qjETZNbHdogVKZ1vFUzvfkJ6j9pBcZiQn9Cfq6swlRa1lJVV6BVoadie9CQrNzCwz9AN3/p5kFuPHSQjqrTHzJu+yHDCFvC7N9xcb3dkhLdwUi4bCXLDYoHGnGiysTnXCk7OUYV+uzNuaqyY4gV3qDIDtquhRlRqLRlqwl6WZTLbQzKU+6ZBYrqhICB65Z1CldVtM5Jw74wiWQeg5hllVhY+bMQIMj9WBecmysDS56zpVbTcV7fPaaR63ja0bi05ymzBgwCT+R/x6mgPM+RW9Kc3Dwjr9rXX83p0REktyRj18JxkByWdCYvb7m4E8ho2jKR5rHAx+vDnUvP52FNDY/SnVTHbXC/GhqOKUbl2PmeKdRylhsZ4JykOS7XA/lPLsyOT4td9O155z/TDydIuLZHJCIdC2VWL2WaahQB4WCJ6GjBVXPEfqDIfOotW6mdtCgTJEe7MR+0Wk++2/78lnkwUYvncsSrILYaZ08lY5Hs0MlwlBTbmXruMJp2jK5yzZFfx/jvCnMld3+IM7MIipyVZoUfVrv/ix246RdZJg79zNe0G8rttTq0XqwZoHPwirL67gej54qrJUnjlAN6ZO/kWK60rbsf21cSdJcbedNYPhW49Zvaawsv3cZJn45RIaXxAsZGQQk91R34+06dB0tLxoTCsIUe0OcnOnFfNcgpUXYm4EWzFNyeJ3htbZmcMsY79pZFcgDeSSyh8JJtEs3AFP7/Hsmpm3OYmXakcDvoeYQPAXCiZbbDdQ7VUvsaD29OWamAM1ggMNsmAfbLObFk5rmrVu7Q442ipHumQXfjxJkIiJyUH8ByyE0ckzzcP5vHOXtuW98tfYdvHyiQgzPOoi3pQe1FiM4i9dx37Wn+uRUs/HUbUF61dJND5w1Bue4ByBeF6j+7DlBVoK/HBJQHkihjjRSJt/TF42QcRcIaNMStNsclxpFbWcN+vTdGoQfbfLya/ROR657I35RzkO5BV/smPIsqY+YubGkxvP3zqS0US+fcP9vpc98E9mAxTcgiXoCa33p/5j5dK7rz31AcsG24bjdFIb865Ymoyz1f3Oy5MhPCY+IOcRStQ4wrl6HTH2/WIbpd/dpKp9CY6fDHskzVDTLGof1oS8MnmAPpIx3I/cmoaPhskX4LnZ8M5RTf/2na+ggrUS9JxiQZ8rW/0gigktRaF3Mlt1xwORR4PLLzldRlRD3bRjsHckp0ifbKuZ1Aoe25rrwZ1crabg4Yv5801pCVOQsiaNyigTYQIQjUbbR9iCVOfaNW/3FLrVieXv2v3Adv5lgxRxOuAAURxWRfjqEKtFPpKSfjWHqUk/m45jSIqs+LplqQ+kAj1vgWYLtwrSNfxTAjDoZa4A6ifTCUrqWSVO5xamtNio+dgJW9e7pBx5nJebggNiXHceXspkxE56TvQH8rCQfRNbRLplUTbpEUsCpa9ZPUVdNW/ikpN7MKxH1ay/0NzuMlT1Bubk5y46riSh2gsrcCdun3ddL8uPldnrXfa0rIz3uZPzH2ZVY82YNaHvo0IfCBgrilMeTJoDpYteatA6xXnLYVpQvAhTZFuh9+FPbH6YaA15QEuSueMuJjkDybNkhBFklPHG6s+GggWcpGjoUOYNXoSSP02l85Rwa9X85eeHONZ+fR+2lo6kyGL9mMSccSb+BjOBDhy6yIyJghf4cRhJSXS6ZDqs8twdILDJRFU21eTlZMyW6rBYfuu+7iL4JMRxxX3U6hSF1C7LDmaxYx1Ok5gxLp18m1g+veq90WtVH3rrWl7a2d+2BAIPIpJddqjvvAwIDxCKw1pefkbYrARfLCWB7It5BDYqJUsv5+mbSNkA8PvoAKzByDSnxG3Ub8cQbXmR+NxkD5gyoVWaLPpW77/tAjwAbKkprkq9gw4a20GacUapLNEpClY8LSSmnSeIVjUHQbHvw0fdP/pCwjEKgl6mv3ut2wXDIc2z6u4JhBW2Qc/72/kMSeWH2KDynVScTq7QXLB+HHg6TNo+dQZRTe0CLzChwUrNotjWOt+gSoLj0GPnEy/HU6thr00jaqT57oYB/z0h1w1Q9w1ONw2zWrsQFQ9SKJNfDNPq8NWIeoOjk4t44jh60sC/lkW3pxB2rJge5VXy/fac5wo2outoJ7+JMIp09ZMkWrNyJQ4Z++LPO5Z8Bl+lwZde93NTV5XjwsTApqVgkE5iYhF185fzO4F5P0hKI2daS63spyCF37PF0etb+km6pGK4BbQCd2cnX9SK2zHk7g6DH109RbQMuuRCIm3pgYItvLXN7h76vp44lTjNV647vPI4S/pmNcNU7nG1S208DCEP7OV4yB1snRBtUZoRTHvle1O7j3cpWpQvhfSgeBmoRKpnVw7xzQeHi4SxoxdQ9QtGvJWTAyelBN5EtYgez3br2An0shbofv+2umDEaZQC5jfLzVdmxZyj57riTesvYFMQEvqC+3iG5yu+9FnUjKsTjfxNXUOb5reuSX6gw29kAXULSBidjdTNethNoI0/rnA6gfqCtUNfPdNW61l832M9xaRpdtVioqKF6eNI9Jzpb9v4zFvJ9bR6gS+fy3Tu+5MXLe1+EfllOp7QqSNK7DZGlEeB6UxlDdBLee//yMpFsi8MKGGA7KDuPr+CzETr6iRfigGtyea6uBkdYzPhkMzKPEvbfazUWYm6rgvPlyQjF4G7NC8Ok8SqJuPOpAHKDlPM42Pij4t0nconw2DlnqFT+J9mJEImmyw30zz81eHxgEg0F9R0wXHdPK48qBVZMbzAMIN1MDr32R28msMyc0llhaV0eb6RnnspdXFWsbwsFc3435BvWk94WNsBYk+Y8SG8bkqINgynTq33YjXRSwYCxUuczXN6gSw7llnxKvHXiiuUtXMXGdXEYApRSEzvCC+X3BNND2+6v2eKUqPDFL/3zp/dfiwqXGL1DH6FhKnyAbZwkeHcoJXeDXKP8Rchs6lFNLDhzKKiHDegXueoaFMc8rUQEJ3LWFM3IyK4hxpCZSWMvU0waR/P0rj7ioyLC62gjOydrtoMwh9j+Q6oEzankGTwuxAIWsaAQ+LEqf3JAjZlaliujKLXJnHdD5GDsW5ILrSkFCAdrfd3qEG72F4Ps377z+Xi6vadne4n6u2iDElwQn9LbfUnfKnWQC2CSb9P0r6C/lOzJXgrAIE8Rx2cGDDbYalY2wKc5rtAZAF5UUE/+BmRthiKweR/RoXEw3zOZrYO+YIQ6Zz2GHzmDF4y7UDpm0TjFI9knSPyjezf3gcztTdLRnQMMwnAp/Q2GqQZfZeLCIo6aqu6aCUNMZmFVxgxauOrNZmp7JrktK7/VkVSaVe/D2axws4h5jmGQVvzF8AHU5ziJ19p9YGg/WK9pEHRqSESLmKhj+nSxmzNoy6tXyumz5DFmNeZQfFNNGmg0UbTMXfigRyGFyUcE9WoiYn6+BDZX5naYF8SC9o/oFEanVttziIQZKFMTs+BfIAo5M19tELeS3wDD+lRpKEvp+O9AjqTBhYo1Y3PRhFMuRU08XTZkhdmgsjM5rXTBWgqDWSvLL/iDjDxkCSxL2mSEzIeDauZX1LcNsCM44qHd/jvmeN9mM40HeR7o8YctgWhqqQENKJfilSEtJ/quCX/jcWToaRQ1Ki0/5TEmEKzoiW9JhVqSLqSr2OJyThS14ZzLbUxH7dbc5N1Yl6OLuhjAYMckuwVxY1KfteOJY/idCfqxwFIFhYGDIlL/7IEUTi0PNbGPvoleKwnwdXl+hw7ATpOkNIdIu9vP9pu1UGpL4pe0eD0163+x5v1oAvwHn+mJkHT5Yv6z/gqdJLRH/Idxn6OOV+0a/B6NfAU0GxkLTL7GZbxkotzdvEdzMulkH+yZZhzAXhtw704nzgQ2LAny+Pgm/YglwJT8dVk1xWQLKyCoTs1uvqtd5W455Ur4IeT0QEam8svdajt9L/qgk6wuhYDBzXXtFlfEONg6AAFbwMPtGevA06los37WXd3M3UPLcr80vCcfX/ItBBOPB5Z150zc0CvgsmPuCF5vn+q7LIwv16FoURkjOQSKyucKez9mmxw2h4oaVm6b7RhFXvIEGVU8FGqh4IsosRRL7rkJR62aSNOFgmkBmaTdHD/kHn6rPHIo5YUUiW202PpO3PPPisxjkUKI8E0jT5cw90NEN7Bcr79oFHJ50/keEtTVDRHuoe71Hjn4Idz+GzmX301sCdiaGOBjqU+z9B23ljsEFA5ZyoUunGn4VF6SOgyQeBB5D4qCcbrxuVEo9i/QiGsIcavXQiyMP8Ehj4wWBwibsbIICfQ+DozdO14qA8rpJx8OluCiSY+ZwLvWv/L6o0geFovVc0NP57Df3Sa21fjenOduTE0sXO2ozTo4I9h8NFcOTM8yxocZIZAOcqFP3oAqyMr/mpd1CLJnL9TAsveKwIGvwfkgMycA3d8YN8d4cBV4h1ZxKNz6WKfMOhX/TlY1o/81kUvJHdd1or0apXKgDWHvrgvw+1fU+zQyz5soLQF2HoLwdMc3hxpPKvim1HTdkg0CjOm7X4V7sxNXcYxulJiW30HEI4/5D0GD5XMGvOhwEmSlPGEZ8b/yP8p5uwdCcKnw8SS5HMolnyROLzsu094mU1bm5gmG9IjSE5op74gknsteCS3jfUMEhL7Ym98ogI12KD5m7S2t1O2rpda+UFWuIhXbo5DhMgsqW3VLauCjUT6TU/DZ1qLFgrv6WLmS7tdwf0iZo1cdjoB45xoMXZcU+ndNHGoHYP56uzP+9+oNJ9NAKEUjbOWzgou2KK7MtD1ta86/QCTVJlz6cpLrSpegw9bA10g718QGtwt3OG7lE+0P8wpplQiRZ/6YgqV9gzpZvJrMFpq/1aagIg1mQTCeki0ENVKat1aTA2y4YmB9cf7EJWuHyNuozdAYaz8fFcemQ5mdOToGpKcP5TcqxTGV0tVPtanOz2IzOn4URb8VVDxnFAiLi6dTEvuWqG0bA7y5YbBjG1jK4XxYEb8NeXL0SqU/yvNG+BMCkuwJQ1RrJRsIzgmQfsxK4jBzEb2zBoMRTqaduSCDp8QS2Wh8FiOIHoG+4HpFkOs2/itqEMj4PoazxHwwvkARIUxdEBBBYAFEqTsDItLoaGV7h/hUs5DC1YTEqHAAAA
```
And for `identity.restorer.esploraEndpoint` I'm using the port of `esplora-liquid` from nigiri that is `5001`, should I use `chopsticks-liquid` that is running on port `3001`?

**Comment by altafan** [comment]
There's already an open PR that fixes the bug on the daemon side, preventing it from crashing.

> And for identity.restorer.esploraEndpoint I'm using the port of esplora-liquid from nigiri that is 5001, should I use chopsticks-liquid that is running on port 3001?

Yes, use `http://localhost:3001` like done in the tdex-sdk [integration test](https://github.com/tdex-network/tdex-sdk/blob/master/test/trade.integration.test.ts#L27).

**Comment by IlSassone** [comment]
> There's already an open PR that fixes the bug on the daemon side, preventing it from crashing. Soon a new rc will be published including the hotfix.
Ok so why it was crashing? We still can't figure out how to make a successful trade, so maybe it could be helpful...

**Comment by altafan** [comment]
@IlSassone  [v0.8.2](https://github.com/tdex-network/tdex-daemon/releases/tag/v0.8.2) has been released. Please, try testing against this version.
